### ISSUE TITLE
Issue with K8s liveness probes

### ISSUE THREAD

**Issue by Sgiath** [mtrudel/bandit#310]
Hi, I am a fan of the project, so I have run a relatively simple Phoenix in production with Bandit since September 2023 (and I have regularly updated the Bandit version in that time). The app used Elixir release inside Docker, which was running in the K8s cluster.

In December 2023, we noticed that the pod was restarted quite regularly without any apparent issue in the logs. After further investigation, we discovered it had been behaving like that from the beginning, and we just noticed it in December. We have determined that the issue is that sometimes the liveness or readiness probes in K8s are timing out, so the K8s decide to restart the pod to make it available again. We had multiple theories about why that happens, but since it didn't happen on our older services, we have tried switching to Cowboy since it was a very quick change. This immediately fixed the issue, and we didn't have any restarts since then.

I am not sure what the issue is since there were no logs in the app; we found out only by inspecting K8s logs, and from them, we have just the info that the request timed out. I am 100 % positive that switching to Cowboy was the only change to fix it. So I did not plan to report it (since I am not even sure what was wrong and I don't have an easy way to reproduce it), but since Bandit is now the new default for Phoenix, I am reporting it now so you are aware of this issue we had with Bandit in production.

The app uses LiveView, and here is the excerpt from the K8s config we have used:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
  namespace: prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: auth
      containers:
        - name: auth
          image: auth:production-master-3252e5c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4040
              name: http
              protocol: TCP

          startupProbe:
            httpGet:
              path: /__startup
              port: http
            periodSeconds: 3
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /__liveness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2

          readinessProbe:
            httpGet:
              path: /__readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 2

          resources:
            requests:
              memory: "225Mi"
              cpu: "30m"
            limits:
              memory: "768Mi"
              cpu: "500m"
```

and this is the implementation of health endpoints (it is included as first plug in the `Endpoint` module):
```elixir
defmodule Web.Plug.Health do
  @behaviour Plug

  import Plug.Conn, only: [halt: 1, send_resp: 3]

  alias Auth.Core.Repo
  alias Ecto.Adapters.SQL
  alias FT.K8S.TrafficDrainHandler

  require Logger

  @impl Plug
  def init(opts), do: opts

  @impl Plug
  def call(%Plug.Conn{} = conn, _opts) do
    case conn.request_path do
      "/__startup" -> health_response(conn, started?())
      "/__liveness" -> health_response(conn, alive?())
      "/__health" -> health_response(conn, alive?())
      "/__readiness" -> health_response(conn, ready?())
      _other -> conn
    end
  end

  defp health_response(conn, true) do
    conn
    |> send_resp(200, "OK")
    |> halt()
  end

  defp health_response(conn, false) do
    conn
    |> send_resp(503, "SERVICE UNAVAILABLE")
    |> halt()
  end

  defp started?, do: alive?()

  defp alive? do
    Repo
    |> SQL.query!("SELECT 1")
    |> is_struct(MyXQL.Result)
  rescue
    _e -> false
  end

  def ready?, do: not TrafficDrainHandler.draining?()
end
```
