### ISSUE TITLE
Every second request from Vector will fail with `Request line HTTP error`

### ISSUE THREAD

**Issue by hauleth** [mtrudel/bandit#503]
I try to implement endpoint for ingesting Prometheus Remote Write protocol. To test my implementation I use [Vector](https://vector.dev), and with simple Plug like that

```elixir
defmodule SamplePlug do
  @behaviour Plug

  def init(_), do: {:ok, []}

  def call(conn, _) do
    dbg Plug.Conn.read_body(conn) # this is important, otherwise it works fine

    Plug.Conn.send_resp(conn, :ok, "")
  end
end
```

And Vector configuration like:

```yaml
data_dir: /tmp/promeduck-vector/
sources:
  source0:
    namespace: vector
    scrape_interval_secs: 1.0
    type: internal_metrics
sinks:
  sink0:
    inputs:
    - source0
    batch:
      aggregate: true
    endpoint: 'http://localhost:4000/ingest/foo/prometheus/v1'
    type: prometheus_remote_write
```

Every *second* request will fail with error like:

```
[error] ** (Bandit.HTTPError) Request line HTTP error: <<217, 0, 254, 217, 0, 206, 217, 0, 4, 50, 53, 138, 98, 3, 254, 217, 0, 254, 217, 0, 206, 217, 0, 4, 53, 49, 138, 99, 3, 0, 215, 254, 139, 2, 254, 139, 2, 174, 139, 2, 0, 10>> module=Bandit.Logger mfa=Bandit.Logger.maybe_log_protocol_error/4 file=lib/bandit/logger.ex line=19 pid=<0.702.0> 
```

And I have no idea how I am supposed to debug that.

With Cowboy it seems to work fine.
